name: Go Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'  # Ensure the correct version is used

      - name: Verify Go version
        run: go version  # Debug step to check the Go version

      - name: Install dependencies
        run: go mod tidy  # Should work with Go 1.11+

      - name: Run tests
        run: go test ./... -v
